### ISSUE TITLE
Lock screen rejects input

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/alpha-testing#10]
Upon resume from sleep the lock screen's password box rejected input until I pressed the power button on my laptop. At that point it stated accept input albeit in laggy fashion. I had managed to get up a virtual keyboard but the input from that was ignored too.

The problem does not preexist the beta although I have just now received updates for gtk2 and gtk3 packages.

Cinnamon 4.0.10
Kernel 5.0.10-050010-generic
slick-greeter 1.2.4-unstable-201903071456~ubuntu18.04.1
HiDPI manually enabled
EDIT: Intel UHD Graphics 620; 3.0 Mesa 18.2.8

**Comment by pizzadude** [comment]
I have the laggy lockscreen issue but not the rejected input issue, with the alpha ppa.

Maybe report the bug here also? https://github.com/linuxmint/cinnamon-screensaver

My specs:
Kernel: Linux 4.18.0-18-generic x86_64
Distro: Linux Mint 19.1 Tessa
CPU:    Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz
        4 cores/threads
        2400.00 MHz
RAM:    7.59 GiB
GPU:    Mesa DRI Intel(R) Ironlake Mobile 
        OpenGL 2.1 Mesa 19.0.1 - padoka PPA
        GLSL 1.20

HIDPI disabled.

**Comment by LinuxOnTheDesktop** [comment]
@pizzadude 

I believe that bugs that are new to the alpha, i.e. introduced by the alpha, are to be reported only here. It might be that the devs are not yet looking at these reports, though.

**Comment by pizzadude** [comment]
Good point.

**Comment by clefebvre** [comment]
This is fixed in today's builds.

**Comment by LinuxOnTheDesktop** [comment]
I am afraid that it isn't. Not unless I make some mistake. For, I have the latest build (as of the time of writing), and the problem remains. The lock screen will accept input, but much of that input does not appear - not without a long delay, anyway - as asterickes in the input box.

**Comment by JosephMcc** [comment]
The problem you describe does still exist on current master. I can reproduce it so the issue is back open.

**Comment by clefebvre** [comment]
This is definitely fixed in the PPA now. https://github.com/linuxmint/muffin/commit/e271164558201d3cb47978ba3fb697c7befb689e

**Comment by LinuxOnTheDesktop** [comment]
I have just now experienced the following mild version of the problem. The machine had been asleep for several hours. Upon waking it up, the lock screen was somewhat slow to display asterisks for my password; there was a delay of some third of a second between key press and the appearance of the character.
