### ISSUE TITLE
Bug: When interacting with a window, the desklet underneath moves regardless if it is visible or not.

### ISSUE THREAD

**Issue by pizzadude** [linuxmint/alpha-testing#11]
In latest cinnamon in the daily builds PPA, I am able to drag the desklet that is underneath a window by moving my mouse and dragging in the same position that a desklet lies underneath, the desklet will be moved. This is a bug, desklets should only be movable if they are visible.

Cinnamon 4.0.10-unstable-201904230123~ubuntu18.04.1
Muffin 4.0.7-unstable-201904240359~ubuntu18.04.1

Specs:
Kernel: Linux 4.18.0-18-generic x86_64
Distro: Linux Mint 19.1 Tessa
CPU:    Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz
        4 cores/threads
        2400.00 MHz
RAM:    7.59 GiB
GPU:    Mesa DRI Intel(R) Ironlake Mobile 
        OpenGL 2.1 Mesa 19.0.1 - padoka PPA
        GLSL 1.20

**Comment by Mintulix** [comment]
Addition: Desklets are also clickable (weather desklet is starting the browser), sometimes the overlaying windows just seem to be permeable.

**Comment by clefebvre** [comment]
Hi @pizzadude @Mintulix, both of these should be fixed on master now. We'll send updates towards the PPA.

**Comment by pizzadude** [comment]
@clefebvre I just updated and I still have this issue, I can still grab and move desklets when another window is covering them.

**Comment by pizzadude** [comment]
The bug is fixed now after today's update.
